# 匿名开关
匿名.启用=false
匿名.玩家进入时随机分配=true
匿名.保留comid=true
匿名.允许其他插件开关=true
匿名.默认匿名状态=false

# 名称池
匿名.名称池文件=anonymous-names.txt
匿名.最少名称数=20
匿名.重复使用名称=true

# 外部检测
检测.提供外部查询=true
检测.外部方法名=isAnonymousEnabled
